// GENERATED by scripts/contract-consumer-artifacts-lib.mjs from contracts/dist/openapi.yaml — DO NOT EDIT BY HAND.
// Regenerate with: npm run contract:types

/** The contract this module was derived from. */
export const CONTRACT = { version: '1.15.0', sha256: 'f37d13fe868d0794f107cd785a0ca587bab22137243d665af912bf02fe0ca7f0' }

/** The consumer this module describes: its operations and its vocabulary. */
export const CONSUMER = 'admin'

/** Every capability some admin operation requires, sorted. */
export const CAPABILITIES = ['configuration:read', 'configuration:write', 'credentials:rotate', 'experiments:read', 'experiments:write', 'log:read', 'merchants:read', 'merchants:write', 'texts:read', 'texts:write']

/** What the contract demands of each admin operation. */
export const OPERATIONS = {
  getOperator: { capabilities: [], idempotent: false, versioned: false },
  listAdminLog: { capabilities: ['log:read'], idempotent: false, versioned: false },
  listMerchants: { capabilities: ['merchants:read'], idempotent: false, versioned: false },
  createMerchant: { capabilities: ['merchants:write'], idempotent: false, versioned: false },
  getMerchant: { capabilities: ['merchants:read'], idempotent: false, versioned: false },
  deactivateMerchant: { capabilities: ['merchants:write'], idempotent: false, versioned: false },
  rotateIngestKey: { capabilities: ['credentials:rotate'], idempotent: false, versioned: false },
  rotatePlatformKey: { capabilities: ['credentials:rotate'], idempotent: false, versioned: false },
  rotatePlatformSecret: { capabilities: ['credentials:rotate'], idempotent: false, versioned: false },
  setKillSwitch: { capabilities: ['merchants:write'], idempotent: false, versioned: false },
  updateMerchantProfile: { capabilities: ['merchants:write'], idempotent: false, versioned: true },
  listMerchantAdminLog: { capabilities: ['log:read'], idempotent: false, versioned: false },
  getMerchantConfiguration: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  publishMerchantConfiguration: { capabilities: ['configuration:write'], idempotent: true, versioned: true },
  listConfigurationVersions: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  getMerchantConfigurationVersion: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  listExperiments: { capabilities: ['experiments:read'], idempotent: false, versioned: false },
  createExperiment: { capabilities: ['experiments:write'], idempotent: false, versioned: false },
  activateExperiment: { capabilities: ['experiments:write'], idempotent: false, versioned: false },
  closeExperiment: { capabilities: ['experiments:write'], idempotent: false, versioned: false },
  listAnchorDiagnostics: { capabilities: ['merchants:read'], idempotent: false, versioned: false },
  listUnmappedAttributeValues: { capabilities: ['merchants:read'], idempotent: false, versioned: false },
  getPlatformConfiguration: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  publishPlatformConfiguration: { capabilities: ['configuration:write'], idempotent: true, versioned: true },
  listPlatformConfigurationVersions: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  getPlatformConfigurationVersion: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  getTreatmentDefaults: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  publishTreatmentDefaults: { capabilities: ['configuration:write'], idempotent: true, versioned: true },
  listTreatmentDefaultsVersions: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  getTreatmentDefaultsVersion: { capabilities: ['configuration:read'], idempotent: false, versioned: false },
  publishText: { capabilities: ['texts:write'], idempotent: true, versioned: false },
  listTextVersions: { capabilities: ['texts:read'], idempotent: false, versioned: false },
  getTextVersion: { capabilities: ['texts:read'], idempotent: false, versioned: false },
  publishMerchantText: { capabilities: ['texts:write'], idempotent: true, versioned: false },
  listMerchantTextVersions: { capabilities: ['texts:read'], idempotent: false, versioned: false },
  getMerchantTextVersion: { capabilities: ['texts:read'], idempotent: false, versioned: false },
}
