// GENERATED by scripts/contract-sync.mjs — interim until OPE-Backend 040 emits generated/contract/
// DO NOT EDIT BY HAND. Regenerate with: npm run contract:sync

/** The contract this module was derived from. */
export const CONTRACT = { version: '1.11.0', sha256: '404fa3c53649232b7323b7cb949c1d548336a7c18fae5cd565c2a2eb6db535b8' }

/** The consumer this module describes: its operations and its vocabulary. */
export const CONSUMER = 'admin'

/** Every capability some admin operation requires, sorted. */
export const CAPABILITIES = ['configuration:read', 'configuration:write', 'credentials:rotate', 'experiments:read', 'experiments:write', 'log:read', 'merchants:read', 'merchants:write', 'texts:read', 'texts:write']

/** What the contract demands of each admin operation. */
export const OPERATIONS = {
  listAdminLog: { capabilities: ['log:read'], idempotent: false },
  listMerchants: { capabilities: ['merchants:read'], idempotent: false },
  createMerchant: { capabilities: ['merchants:write'], idempotent: false },
  getMerchant: { capabilities: ['merchants:read'], idempotent: false },
  deactivateMerchant: { capabilities: ['merchants:write'], idempotent: false },
  rotateIngestKey: { capabilities: ['credentials:rotate'], idempotent: false },
  rotatePlatformKey: { capabilities: ['credentials:rotate'], idempotent: false },
  rotatePlatformSecret: { capabilities: ['credentials:rotate'], idempotent: false },
  setKillSwitch: { capabilities: ['merchants:write'], idempotent: false },
  listMerchantAdminLog: { capabilities: ['log:read'], idempotent: false },
  getMerchantConfiguration: { capabilities: ['configuration:read'], idempotent: false },
  publishMerchantConfiguration: { capabilities: ['configuration:write'], idempotent: true },
  listConfigurationVersions: { capabilities: ['configuration:read'], idempotent: false },
  listExperiments: { capabilities: ['experiments:read'], idempotent: false },
  createExperiment: { capabilities: ['experiments:write'], idempotent: false },
  activateExperiment: { capabilities: ['experiments:write'], idempotent: false },
  closeExperiment: { capabilities: ['experiments:write'], idempotent: false },
  listAnchorDiagnostics: { capabilities: ['merchants:read'], idempotent: false },
  listUnmappedAttributeValues: { capabilities: ['merchants:read'], idempotent: false },
  getPlatformConfiguration: { capabilities: ['configuration:read'], idempotent: false },
  publishPlatformConfiguration: { capabilities: ['configuration:write'], idempotent: true },
  listPlatformConfigurationVersions: { capabilities: ['configuration:read'], idempotent: false },
  getPlatformConfigurationVersion: { capabilities: ['configuration:read'], idempotent: false },
  getTreatmentDefaults: { capabilities: ['configuration:read'], idempotent: false },
  publishTreatmentDefaults: { capabilities: ['configuration:write'], idempotent: true },
  listTreatmentDefaultsVersions: { capabilities: ['configuration:read'], idempotent: false },
  getTreatmentDefaultsVersion: { capabilities: ['configuration:read'], idempotent: false },
  publishText: { capabilities: ['texts:write'], idempotent: true },
  listTextVersions: { capabilities: ['texts:read'], idempotent: false },
  getTextVersion: { capabilities: ['texts:read'], idempotent: false },
  publishMerchantText: { capabilities: ['texts:write'], idempotent: true },
  listMerchantTextVersions: { capabilities: ['texts:read'], idempotent: false },
  getMerchantTextVersion: { capabilities: ['texts:read'], idempotent: false },
}
