// GENERATED by scripts/contract-consumer-artifacts-lib.mjs from contracts/dist/openapi.yaml — DO NOT EDIT BY HAND.
// Regenerate with: npm run contract:types

/** The contract this module was derived from. */
export declare const CONTRACT: {
  readonly version: '1.13.0'
  readonly sha256: '06ea91708eac4c2b4f3e2447c8026b030a49e2963ae0d43c7ac4cba13eb06289'
}

/** The consumer this module describes: its operations and its vocabulary. */
export declare const CONSUMER: 'admin'

/** Every capability some admin operation requires, sorted. */
export declare const CAPABILITIES: readonly ['configuration:read', 'configuration:write', 'credentials:rotate', 'experiments:read', 'experiments:write', 'log:read', 'merchants:read', 'merchants:write', 'texts:read', 'texts:write']
export type Capability = (typeof CAPABILITIES)[number]

/** What the contract demands of each admin operation. */
export declare const OPERATIONS: {
  readonly getOperator: {
    readonly capabilities: readonly []
    readonly idempotent: false
  }
  readonly listAdminLog: {
    readonly capabilities: readonly ['log:read']
    readonly idempotent: false
  }
  readonly listMerchants: {
    readonly capabilities: readonly ['merchants:read']
    readonly idempotent: false
  }
  readonly createMerchant: {
    readonly capabilities: readonly ['merchants:write']
    readonly idempotent: false
  }
  readonly getMerchant: {
    readonly capabilities: readonly ['merchants:read']
    readonly idempotent: false
  }
  readonly deactivateMerchant: {
    readonly capabilities: readonly ['merchants:write']
    readonly idempotent: false
  }
  readonly rotateIngestKey: {
    readonly capabilities: readonly ['credentials:rotate']
    readonly idempotent: false
  }
  readonly rotatePlatformKey: {
    readonly capabilities: readonly ['credentials:rotate']
    readonly idempotent: false
  }
  readonly rotatePlatformSecret: {
    readonly capabilities: readonly ['credentials:rotate']
    readonly idempotent: false
  }
  readonly setKillSwitch: {
    readonly capabilities: readonly ['merchants:write']
    readonly idempotent: false
  }
  readonly updateMerchantProfile: {
    readonly capabilities: readonly ['merchants:write']
    readonly idempotent: false
  }
  readonly listMerchantAdminLog: {
    readonly capabilities: readonly ['log:read']
    readonly idempotent: false
  }
  readonly getMerchantConfiguration: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly publishMerchantConfiguration: {
    readonly capabilities: readonly ['configuration:write']
    readonly idempotent: true
  }
  readonly listConfigurationVersions: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly listExperiments: {
    readonly capabilities: readonly ['experiments:read']
    readonly idempotent: false
  }
  readonly createExperiment: {
    readonly capabilities: readonly ['experiments:write']
    readonly idempotent: false
  }
  readonly activateExperiment: {
    readonly capabilities: readonly ['experiments:write']
    readonly idempotent: false
  }
  readonly closeExperiment: {
    readonly capabilities: readonly ['experiments:write']
    readonly idempotent: false
  }
  readonly listAnchorDiagnostics: {
    readonly capabilities: readonly ['merchants:read']
    readonly idempotent: false
  }
  readonly listUnmappedAttributeValues: {
    readonly capabilities: readonly ['merchants:read']
    readonly idempotent: false
  }
  readonly getPlatformConfiguration: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly publishPlatformConfiguration: {
    readonly capabilities: readonly ['configuration:write']
    readonly idempotent: true
  }
  readonly listPlatformConfigurationVersions: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly getPlatformConfigurationVersion: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly getTreatmentDefaults: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly publishTreatmentDefaults: {
    readonly capabilities: readonly ['configuration:write']
    readonly idempotent: true
  }
  readonly listTreatmentDefaultsVersions: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly getTreatmentDefaultsVersion: {
    readonly capabilities: readonly ['configuration:read']
    readonly idempotent: false
  }
  readonly publishText: {
    readonly capabilities: readonly ['texts:write']
    readonly idempotent: true
  }
  readonly listTextVersions: {
    readonly capabilities: readonly ['texts:read']
    readonly idempotent: false
  }
  readonly getTextVersion: {
    readonly capabilities: readonly ['texts:read']
    readonly idempotent: false
  }
  readonly publishMerchantText: {
    readonly capabilities: readonly ['texts:write']
    readonly idempotent: true
  }
  readonly listMerchantTextVersions: {
    readonly capabilities: readonly ['texts:read']
    readonly idempotent: false
  }
  readonly getMerchantTextVersion: {
    readonly capabilities: readonly ['texts:read']
    readonly idempotent: false
  }
}
export type OperationId = keyof typeof OPERATIONS
