// GENERATED by scripts/contract-consumer-artifacts-lib.mjs from contracts/dist/openapi.yaml — DO NOT EDIT BY HAND.
// Regenerate with: npm run contract:types

/** The contract this module was derived from. */
export const CONTRACT = { version: '1.15.0', sha256: 'f37d13fe868d0794f107cd785a0ca587bab22137243d665af912bf02fe0ca7f0' }

/** What a form can verify locally of each request body of the admin consumer (layer 1). */
export const CONSTRAINTS = {
  "AnchorMap": {
    "required": [],
    "fields": {
      "variant_selector": {
        "type": "object",
        "ref": "AnchorSelectors"
      },
      "price": {
        "type": "object",
        "ref": "AnchorSelectors"
      },
      "cta": {
        "type": "object",
        "ref": "AnchorSelectors"
      },
      "policies": {
        "type": "object",
        "ref": "AnchorSelectors"
      }
    }
  },
  "AnchorSelectors": {
    "required": [
      "selectors"
    ],
    "fields": {
      "selectors": {
        "type": "array",
        "minItems": 1,
        "maxItems": 8,
        "items": {
          "type": "string",
          "minLength": 1,
          "maxLength": 255
        }
      }
    }
  },
  "AttributeLabel": {
    "required": [
      "label",
      "value"
    ],
    "fields": {
      "label": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      },
      "value": {
        "type": "string",
        "enum": [
          "combed-cotton",
          "jersey",
          "linen",
          "denim",
          "leather"
        ]
      }
    }
  },
  "BarrierRule": {
    "required": [
      "id",
      "barrier",
      "strength",
      "when"
    ],
    "fields": {
      "id": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "barrier": {
        "type": "string",
        "enum": [
          "fit",
          "price",
          "returns"
        ]
      },
      "strength": {
        "type": "string",
        "enum": [
          "strong",
          "supporting"
        ]
      },
      "weight": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "when": {
        "type": "object",
        "ref": "Condition"
      }
    }
  },
  "CommercialPolicy": {
    "required": [
      "version",
      "maxIncentiveShare",
      "incentiveLadderShare",
      "directIncentiveOnPrice",
      "returnRisk",
      "highIntent",
      "abandonment",
      "interventionsPerSession",
      "cooldownSeconds",
      "interventionsPerVisitorPerDay"
    ],
    "fields": {
      "version": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "maxIncentiveShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "incentiveLadderShare": {
        "type": "array",
        "minItems": 1,
        "maxItems": 8,
        "items": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "marginShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "directIncentiveOnPrice": {
        "type": "boolean"
      },
      "returnRisk": {
        "type": "object",
        "ref": "Condition"
      },
      "highIntent": {
        "type": "string",
        "enum": [
          "from-cart",
          "from-checkout",
          "never"
        ]
      },
      "abandonment": {
        "type": "string",
        "enum": [
          "nothing",
          "reassure-returns"
        ]
      },
      "interventionsPerSession": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      },
      "cooldownSeconds": {
        "type": "integer",
        "minimum": 0,
        "maximum": 86400
      },
      "interventionsPerVisitorPerDay": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      }
    }
  },
  "CommercialPolicyDeclared": {
    "required": [
      "version"
    ],
    "fields": {
      "version": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "maxIncentiveShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "incentiveLadderShare": {
        "type": "array",
        "minItems": 1,
        "maxItems": 8,
        "items": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "marginShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "directIncentiveOnPrice": {
        "type": "boolean"
      },
      "returnRisk": {
        "type": "object",
        "ref": "Condition"
      },
      "highIntent": {
        "type": "string",
        "enum": [
          "from-cart",
          "from-checkout",
          "never"
        ]
      },
      "abandonment": {
        "type": "string",
        "enum": [
          "nothing",
          "reassure-returns"
        ]
      },
      "interventionsPerSession": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      },
      "cooldownSeconds": {
        "type": "integer",
        "minimum": 0,
        "maximum": 86400
      },
      "interventionsPerVisitorPerDay": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      }
    }
  },
  "Condition": {
    "required": [],
    "fields": {}
  },
  "CredentialRotation": {
    "required": [],
    "fields": {
      "graceSeconds": {
        "type": "integer",
        "minimum": 0
      }
    }
  },
  "DecisionPolicy": {
    "required": [
      "version",
      "rules",
      "weights",
      "readingSeconds",
      "threshold",
      "priority",
      "evidence"
    ],
    "fields": {
      "version": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "rules": {
        "type": "array",
        "minItems": 1,
        "maxItems": 64,
        "items": {
          "type": "object",
          "ref": "BarrierRule"
        }
      },
      "weights": {
        "type": "object",
        "ref": "PolicyWeights"
      },
      "readingSeconds": {
        "type": "number",
        "minimum": 0,
        "maximum": 3600
      },
      "threshold": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "priority": {
        "type": "array",
        "minItems": 1,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "fit",
            "price",
            "returns"
          ]
        }
      },
      "evidence": {
        "type": "object",
        "ref": "PolicyEvidence"
      }
    }
  },
  "DecisionPolicyDeclared": {
    "required": [
      "version"
    ],
    "fields": {
      "version": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "rules": {
        "type": "array",
        "minItems": 1,
        "maxItems": 64,
        "items": {
          "type": "object",
          "ref": "BarrierRule"
        }
      },
      "weights": {
        "type": "object",
        "ref": "PolicyWeights"
      },
      "readingSeconds": {
        "type": "number",
        "minimum": 0,
        "maximum": 3600
      },
      "threshold": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "priority": {
        "type": "array",
        "minItems": 1,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "fit",
            "price",
            "returns"
          ]
        }
      },
      "evidence": {
        "type": "object",
        "ref": "PolicyEvidence"
      }
    }
  },
  "DedupWindow": {
    "required": [
      "ttlMs",
      "maxIds"
    ],
    "fields": {
      "ttlMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "maxIds": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      }
    }
  },
  "EvidenceProfile": {
    "required": [
      "returnsPolicy",
      "fitData",
      "authorizedAttributes"
    ],
    "fields": {
      "returnsPolicy": {
        "type": "boolean"
      },
      "fitData": {
        "type": "boolean"
      },
      "authorizedAttributes": {
        "type": "array",
        "maxItems": 32,
        "items": {
          "type": "string",
          "maxLength": 64
        }
      }
    }
  },
  "EvidenceProfileDeclared": {
    "required": [],
    "fields": {
      "returnsPolicy": {
        "type": "boolean"
      },
      "fitData": {
        "type": "boolean"
      },
      "authorizedAttributes": {
        "type": "array",
        "maxItems": 32,
        "items": {
          "type": "string",
          "maxLength": 64
        }
      }
    }
  },
  "ExperimentCreate": {
    "required": [
      "treatmentShare",
      "seed",
      "targetSample"
    ],
    "fields": {
      "treatmentShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "seed": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "targetSample": {
        "type": "integer",
        "minimum": 1
      },
      "cuts": {
        "type": "array",
        "maxItems": 10,
        "items": {
          "type": "number",
          "maximum": 1
        }
      }
    }
  },
  "Freshness": {
    "required": [
      "catalogMs",
      "stockAndPriceMs"
    ],
    "fields": {
      "catalogMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "stockAndPriceMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      }
    }
  },
  "FreshnessDeclared": {
    "required": [],
    "fields": {
      "catalogMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "stockAndPriceMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      }
    }
  },
  "KillSwitch": {
    "required": [
      "enabled"
    ],
    "fields": {
      "enabled": {
        "type": "boolean"
      }
    }
  },
  "Locales": {
    "required": [
      "supported"
    ],
    "fields": {
      "supported": {
        "type": "array",
        "maxItems": 32,
        "items": {
          "type": "string",
          "maxLength": 35,
          "pattern": "^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$"
        }
      },
      "fallback": {
        "type": "string",
        "maxLength": 35,
        "pattern": "^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$"
      }
    }
  },
  "MerchantConfigurationDeclared": {
    "required": [],
    "fields": {
      "freshness": {
        "type": "object",
        "ref": "FreshnessDeclared"
      },
      "syncLevel": {
        "type": "object",
        "ref": "SyncLevelRulesDeclared"
      },
      "holdoutShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "decisionPolicy": {
        "type": "object",
        "ref": "DecisionPolicyDeclared"
      },
      "commercialPolicy": {
        "type": "object",
        "ref": "CommercialPolicyDeclared"
      },
      "evidenceProfile": {
        "type": "object",
        "ref": "EvidenceProfileDeclared"
      },
      "surfaces": {
        "type": "array",
        "minItems": 1,
        "maxItems": 2,
        "items": {
          "type": "string",
          "enum": [
            "product",
            "cart"
          ]
        }
      },
      "barriers": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string",
          "enum": [
            "fit",
            "price",
            "returns"
          ]
        }
      },
      "syncStrategy": {
        "type": "object",
        "ref": "SyncStrategyDeclared"
      },
      "locales": {
        "type": "object",
        "ref": "Locales"
      },
      "attributeLabels": {
        "type": "array",
        "maxItems": 256,
        "items": {
          "type": "object",
          "ref": "AttributeLabel"
        }
      },
      "anchors": {
        "type": "object",
        "ref": "AnchorMap"
      }
    }
  },
  "MerchantConfigurationInput": {
    "required": [
      "declared"
    ],
    "fields": {
      "declared": {
        "type": "object",
        "ref": "MerchantConfigurationDeclared"
      },
      "corrective": {
        "type": "boolean"
      },
      "reason": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      }
    }
  },
  "MerchantContact": {
    "required": [
      "name",
      "email"
    ],
    "fields": {
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 120
      },
      "email": {
        "type": "string",
        "minLength": 3,
        "maxLength": 254,
        "format": "email"
      },
      "phone": {
        "type": "string",
        "minLength": 1,
        "maxLength": 32
      },
      "role": {
        "type": "string",
        "minLength": 1,
        "maxLength": 80
      }
    }
  },
  "MerchantCreate": {
    "required": [
      "origins",
      "signature",
      "displayName"
    ],
    "fields": {
      "displayName": {
        "type": "string",
        "minLength": 1,
        "maxLength": 120
      },
      "storeUrl": {
        "type": "string",
        "minLength": 1,
        "maxLength": 255,
        "pattern": "^https?://"
      },
      "contact": {
        "type": "object",
        "ref": "MerchantContact"
      },
      "notes": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000
      },
      "origins": {
        "type": "array",
        "minItems": 1,
        "maxItems": 20,
        "items": {
          "type": "string",
          "maxLength": 255
        }
      },
      "signature": {
        "type": "boolean"
      }
    }
  },
  "MerchantProfileInput": {
    "required": [
      "displayName"
    ],
    "fields": {
      "displayName": {
        "type": "string",
        "minLength": 1,
        "maxLength": 120
      },
      "storeUrl": {
        "type": "string",
        "minLength": 1,
        "maxLength": 255,
        "pattern": "^https?://"
      },
      "contact": {
        "type": "object",
        "ref": "MerchantContact"
      },
      "notes": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000
      }
    }
  },
  "MerchantTextInput": {
    "required": [
      "family",
      "locale"
    ],
    "fields": {
      "family": {
        "type": "string",
        "minLength": 5,
        "maxLength": 64,
        "pattern": "^[a-z]+\\.[a-z_]+\\.[a-z_]+$"
      },
      "attributeValue": {
        "type": "string",
        "enum": [
          "combed-cotton",
          "jersey",
          "linen",
          "denim",
          "leather"
        ]
      },
      "locale": {
        "type": "string",
        "maxLength": 35,
        "pattern": "^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$"
      },
      "text": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      },
      "remove": {
        "type": "boolean",
        "enum": [
          true
        ]
      },
      "corrective": {
        "type": "boolean"
      },
      "reason": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      }
    }
  },
  "PlatformConfigurationContent": {
    "required": [
      "dedupWindow",
      "eventPastToleranceMs",
      "clockSkewToleranceMs",
      "sessionDurationMs",
      "visitorWindowMs",
      "signatureWindowMs",
      "rotationGraceMaxMs",
      "anchorDiagnosticsKept",
      "unmappedValuesKept",
      "retryAfterSeconds"
    ],
    "fields": {
      "dedupWindow": {
        "type": "object",
        "ref": "DedupWindow"
      },
      "eventPastToleranceMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "clockSkewToleranceMs": {
        "type": "integer",
        "minimum": 0,
        "maximum": 31536000000
      },
      "sessionDurationMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "visitorWindowMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "signatureWindowMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "rotationGraceMaxMs": {
        "type": "integer",
        "minimum": 0,
        "maximum": 31536000000
      },
      "anchorDiagnosticsKept": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      },
      "unmappedValuesKept": {
        "type": "integer",
        "minimum": 1,
        "maximum": 1000000
      },
      "retryAfterSeconds": {
        "type": "integer",
        "minimum": 1,
        "maximum": 3600
      }
    }
  },
  "PlatformConfigurationInput": {
    "required": [
      "content"
    ],
    "fields": {
      "content": {
        "type": "object",
        "ref": "PlatformConfigurationContent"
      },
      "corrective": {
        "type": "boolean"
      },
      "reason": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      }
    }
  },
  "PolicyEvidence": {
    "required": [],
    "fields": {
      "freshStockAndPrice": {
        "type": "array",
        "minItems": 1,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "fit",
            "price",
            "returns"
          ]
        }
      },
      "availableVariant": {
        "type": "array",
        "minItems": 1,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "fit",
            "price",
            "returns"
          ]
        }
      }
    }
  },
  "PolicyWeights": {
    "required": [
      "strong",
      "supporting"
    ],
    "fields": {
      "strong": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "supporting": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      }
    }
  },
  "SyncLevelRules": {
    "required": [
      "receiptsKept",
      "noDataAfterMs",
      "minutesLevelMaxAgeMs",
      "minutesLevelMedianIntervalMs",
      "minutesLevelMinReceipts"
    ],
    "fields": {
      "receiptsKept": {
        "type": "integer",
        "minimum": 2,
        "maximum": 1000000
      },
      "noDataAfterMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "minutesLevelMaxAgeMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "minutesLevelMedianIntervalMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "minutesLevelMinReceipts": {
        "type": "integer",
        "minimum": 2,
        "maximum": 1000000
      }
    }
  },
  "SyncLevelRulesDeclared": {
    "required": [],
    "fields": {
      "receiptsKept": {
        "type": "integer",
        "minimum": 2,
        "maximum": 1000000
      },
      "noDataAfterMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "minutesLevelMaxAgeMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "minutesLevelMedianIntervalMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 31536000000
      },
      "minutesLevelMinReceipts": {
        "type": "integer",
        "minimum": 2,
        "maximum": 1000000
      }
    }
  },
  "SyncStrategy": {
    "required": [
      "catalog",
      "stockAndPrice",
      "orders",
      "returns"
    ],
    "fields": {
      "catalog": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      },
      "stockAndPrice": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      },
      "orders": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      },
      "returns": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      }
    }
  },
  "SyncStrategyDeclared": {
    "required": [],
    "fields": {
      "catalog": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      },
      "stockAndPrice": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      },
      "orders": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      },
      "returns": {
        "type": "string",
        "enum": [
          "push",
          "pull",
          "subscribe"
        ]
      }
    }
  },
  "TextInput": {
    "required": [
      "family",
      "locale",
      "text"
    ],
    "fields": {
      "family": {
        "type": "string",
        "minLength": 5,
        "maxLength": 64,
        "pattern": "^[a-z]+\\.[a-z_]+\\.[a-z_]+$"
      },
      "attributeValue": {
        "type": "string",
        "enum": [
          "combed-cotton",
          "jersey",
          "linen",
          "denim",
          "leather"
        ]
      },
      "locale": {
        "type": "string",
        "maxLength": 35,
        "pattern": "^[A-Za-z]{2,8}(-[A-Za-z0-9]{1,8})*$"
      },
      "text": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      },
      "corrective": {
        "type": "boolean"
      },
      "reason": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      }
    }
  },
  "TreatmentDefaultsContent": {
    "required": [
      "freshness",
      "syncLevel",
      "holdoutShare",
      "decisionPolicy",
      "commercialPolicy",
      "evidenceProfile",
      "surfaces",
      "barriers",
      "syncStrategy",
      "locales"
    ],
    "fields": {
      "freshness": {
        "type": "object",
        "ref": "Freshness"
      },
      "syncLevel": {
        "type": "object",
        "ref": "SyncLevelRules"
      },
      "holdoutShare": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      },
      "decisionPolicy": {
        "type": "object",
        "ref": "DecisionPolicy"
      },
      "commercialPolicy": {
        "type": "object",
        "ref": "CommercialPolicy"
      },
      "evidenceProfile": {
        "type": "object",
        "ref": "EvidenceProfile"
      },
      "surfaces": {
        "type": "array",
        "minItems": 1,
        "maxItems": 2,
        "items": {
          "type": "string",
          "enum": [
            "product",
            "cart"
          ]
        }
      },
      "barriers": {
        "type": "array",
        "minItems": 1,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "fit",
            "price",
            "returns"
          ]
        }
      },
      "syncStrategy": {
        "type": "object",
        "ref": "SyncStrategy"
      },
      "locales": {
        "type": "object",
        "ref": "Locales"
      }
    }
  },
  "TreatmentDefaultsInput": {
    "required": [
      "content"
    ],
    "fields": {
      "content": {
        "type": "object",
        "ref": "TreatmentDefaultsContent"
      },
      "corrective": {
        "type": "boolean"
      },
      "reason": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      }
    }
  }
}
