// GENERATED by scripts/contract-sync.mjs — interim until OPE-Backend 040 emits generated/contract/
// DO NOT EDIT BY HAND. Regenerate with: npm run contract:sync

/** The contract this module was derived from. */
export declare const CONTRACT: {
  readonly version: '1.11.0'
  readonly sha256: '404fa3c53649232b7323b7cb949c1d548336a7c18fae5cd565c2a2eb6db535b8'
}

/** What the contract demands of one field; the same shape `@ope/core` validates with. */
export type FieldConstraints = {
  readonly type?: string
  readonly ref?: string
  readonly minLength?: number
  readonly maxLength?: number
  readonly pattern?: string
  readonly minimum?: number
  readonly maximum?: number
  readonly minItems?: number
  readonly maxItems?: number
  readonly items?: FieldConstraints
  readonly enum?: readonly (string | number | boolean)[]
  readonly format?: string
}

/** What the contract demands of one request body. */
export type MessageConstraints = {
  readonly required: readonly string[]
  readonly fields: Readonly<Record<string, FieldConstraints>>
}

/** What a form can verify locally of each request body of the admin consumer (layer 1). */
export declare const CONSTRAINTS: {
  readonly AnchorMap: MessageConstraints
  readonly AnchorSelectors: MessageConstraints
  readonly AttributeLabel: MessageConstraints
  readonly BarrierRule: MessageConstraints
  readonly CommercialPolicy: MessageConstraints
  readonly CommercialPolicyDeclared: MessageConstraints
  readonly Condition: MessageConstraints
  readonly CredentialRotation: MessageConstraints
  readonly DecisionPolicy: MessageConstraints
  readonly DecisionPolicyDeclared: MessageConstraints
  readonly DedupWindow: MessageConstraints
  readonly EvidenceProfile: MessageConstraints
  readonly EvidenceProfileDeclared: MessageConstraints
  readonly ExperimentCreate: MessageConstraints
  readonly Freshness: MessageConstraints
  readonly FreshnessDeclared: MessageConstraints
  readonly KillSwitch: MessageConstraints
  readonly Locales: MessageConstraints
  readonly MerchantConfigurationDeclared: MessageConstraints
  readonly MerchantConfigurationInput: MessageConstraints
  readonly MerchantCreate: MessageConstraints
  readonly MerchantTextInput: MessageConstraints
  readonly PlatformConfigurationContent: MessageConstraints
  readonly PlatformConfigurationInput: MessageConstraints
  readonly PolicyEvidence: MessageConstraints
  readonly PolicyWeights: MessageConstraints
  readonly SyncLevelRules: MessageConstraints
  readonly SyncLevelRulesDeclared: MessageConstraints
  readonly SyncStrategy: MessageConstraints
  readonly SyncStrategyDeclared: MessageConstraints
  readonly TextInput: MessageConstraints
  readonly TreatmentDefaultsContent: MessageConstraints
  readonly TreatmentDefaultsInput: MessageConstraints
}
export type ConstrainedSchema = keyof typeof CONSTRAINTS
