import { execFileSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, describe, expect, it } from 'vitest'

/**
 * **El sincronizador copia, y si no hay qué copiar, falla** (`OW-5`, enmendada
 * en la 007). Corre el programa de verdad, con `--from` sobre una carpeta de
 * backend de mentira y con `cwd` en una carpeta propia, así que nunca toca
 * `contracts/ope/` de este repositorio.
 */

const SCRIPT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'scripts',
  'contract-sync.mjs',
)
const EIGHT = [
  'openapi.yaml',
  'api.d.ts',
  'problem-types.d.ts',
  'capabilities.js',
  'capabilities.d.ts',
  'constraints.js',
  'constraints.d.ts',
  'identity.json',
]

const scratch = []
afterEach(() => {
  for (const dir of scratch.splice(0)) rmSync(dir, { recursive: true, force: true })
})

function fakeBackend({ emitted = true, without = [] } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'ope-backend-'))
  scratch.push(dir)
  if (emitted) {
    mkdirSync(join(dir, 'generated', 'contract'), { recursive: true })
    for (const name of EIGHT) {
      if (without.includes(name)) continue
      const content =
        name === 'openapi.yaml'
          ? '# GENERATED by scripts/x.mjs from y\nopenapi: 3.1.0\ninfo:\n  title: f\n  version: 9.9.9\npaths: {}\n'
          : `// ${name}\n`
      writeFileSync(join(dir, 'generated', 'contract', name), content, 'utf8')
    }
  }
  return dir
}

function run(backend) {
  const root = mkdtempSync(join(tmpdir(), 'ope-web-'))
  scratch.push(root)
  try {
    const stdout = execFileSync(process.execPath, [SCRIPT, '--from', backend], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    return { root, status: 0, output: stdout }
  } catch (error) {
    return { root, status: error.status, output: `${error.stdout}\n${error.stderr}` }
  }
}

describe('contract-sync', () => {
  it('copies the eight files of generated/contract/ as they are, and writes the README', () => {
    const { root, status, output } = run(fakeBackend())
    expect(status, output).toBe(0)
    const target = join(root, 'contracts', 'ope')
    expect(readdirSync(target).sort()).toEqual([...EIGHT, 'README.md'].sort())
    expect(readFileSync(join(target, 'capabilities.js'), 'utf8')).toBe('// capabilities.js\n')
    expect(readFileSync(join(target, 'README.md'), 'utf8')).toContain('`9.9.9`')
    expect(output).not.toContain('emitido')
  })

  it('fails naming contract:types when the backend has no generated/contract/', () => {
    const { root, status, output } = run(fakeBackend({ emitted: false }))
    expect(status).not.toBe(0)
    expect(output).toContain('generated/contract/')
    expect(output).toContain('npm run contract:types')
    expect(() => readdirSync(join(root, 'contracts', 'ope'))).toThrow()
  })

  it('fails when one of the eight is missing: the backend emits them together', () => {
    const { status, output } = run(fakeBackend({ without: ['constraints.js'] }))
    expect(status).not.toBe(0)
    expect(output).toContain('constraints.js')
    expect(output).toContain('npm run contract:types')
  })
})
