/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar artículos
         * @description Ordenado por nombre ascendente.
         *
         *     **`search` busca por nombre, parcial e insensible a mayúsculas.**
         */
        get: operations["listArticles"];
        put?: never;
        /**
         * Crear un artículo
         * @description El nombre no puede repetirse: si ya existe otro con ese nombre, responde `409` con
         *     `CATALOG_ENTRY_DUPLICATE`.
         *
         *     **Exige `Idempotency-Key`.** Con la misma clave y el mismo cuerpo devuelve lo que
         *     devolvió la primera vez, sin crear otro artículo.
         */
        post: operations["createArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        /**
         * Ver un artículo
         * @description Devuelve el `ETag` del artículo. **Editarlo exige devolverlo**, así que esta lectura es
         *     el paso previo obligado de `updateArticle` — y por eso la edición no puede ser un
         *     diálogo que se abre sin haber pedido nada (`GR-42`).
         */
        get: operations["getArticle"];
        /**
         * Editar un artículo
         * @description **Exige `If-Match`**, así que hay que haber leído el artículo antes. Sin eso responde
         *     `428`: nunca se aplica un cambio a ciegas.
         *
         *     No exige `Idempotency-Key`: guardar dos veces el mismo cuerpo sobre la misma versión
         *     deja el mismo estado, y la segunda vez el `If-Match` ya no coincide. La clave se reserva
         *     para lo que aplicado dos veces cuenta dos veces.
         */
        put: operations["updateArticle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}/deactivation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desactivar un artículo
         * @description Lo saca de circulación sin borrarlo: sigue en el catálogo y en la historia, con
         *     `active: false`.
         *
         *     **No exige `Idempotency-Key`**, y es la diferencia con dar de alta: desactivar dos veces
         *     el mismo artículo deja el mismo estado, así que un reintento no puede duplicar nada.
         *     La clave se reserva para lo que aplicado dos veces cuenta dos veces.
         */
        post: operations["deactivateArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}/activation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activar un artículo
         * @description Lo vuelve a poner en circulación.
         *
         *     **Tampoco exige `Idempotency-Key`**, por lo mismo que su inversa: aplicarla dos veces
         *     deja el mismo estado.
         */
        post: operations["activateArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Importe monetario, **como texto decimal**. Nunca como número: un flotante pierde
         *     centavos, y el error se propaga a todo lo que se calcule con él.
         *
         *     Tiene nombre propio para que **de qué tipo es un campo salga del contrato**: quien
         *     lo dibuja no elige cómo se ve un importe, lo deriva.
         */
        Amount: string;
        Article: {
            /** Format: int64 */
            id: number;
            name: string;
            price: components["schemas"]["Amount"];
            discountedPrice?: components["schemas"]["Amount"];
            /**
             * Format: int32
             * @description Cuántas unidades hay. Opcional — no todo artículo se cuenta.
             */
            stock?: number;
            /** @description Si se puede usar. Uno inactivo se ve pero no se elige. */
            active: boolean;
        };
        ArticleCreate: {
            name: string;
            price: components["schemas"]["Amount"];
            discountedPrice?: components["schemas"]["Amount"];
            /** Format: int32 */
            stock?: number;
            /** @default true */
            active: boolean;
        };
        Meta: {
            /** @description Lo que se cita para rastrear la operación. */
            requestId: string;
        };
        /**
         * @description Lo mismo que `Meta` más la paginación. **No compone con `allOf` sobre `Meta`** porque
         *     `Meta` es un objeto cerrado y cada rama de un `allOf` se evalúa contra el objeto completo:
         *     la rama de `Meta` rechazaría `page` y los totales. Se repite `requestId` a propósito.
         */
        PageMeta: {
            requestId: string;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /**
                 * @description Castellano, para una persona. **No ramificar sobre esto**: es texto de presentación
                 *     y puede cambiar sin que sea un cambio de contrato.
                 */
                message: string;
                requestId: string;
                /** @description Sólo en `VALIDATION_FAILED`. Va a los campos del formulario. */
                fields?: {
                    field: string;
                    code: string;
                    message: string;
                }[];
            };
        };
        /**
         * @description Enum cerrado. Es sobre esto que se ramifica.
         * @enum {string}
         */
        ErrorCode: "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_FAILED" | "CATALOG_ENTRY_DUPLICATE" | "ARTICLE_ALREADY_INACTIVE" | "ARTICLE_ALREADY_ACTIVE" | "DISCOUNT_ABOVE_PRICE" | "STALE_VERSION" | "IDEMPOTENCY_KEY_REUSE" | "INTERNAL_ERROR";
    };
    responses: {
        /** @description Sin sesión. */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHENTICATED",
                 *         "message": "Hay que volver a entrar.",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La sesión no habilita esta operación. */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "La sesión no habilita esta operación.",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No existe. */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "No se encontró el artículo.",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ya existe otro con ese nombre. */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "CATALOG_ENTRY_DUPLICATE",
                 *         "message": "Ya existe un artículo con ese nombre.",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description El `If-Match` enviado no coincide con la versión actual del recurso: cambió entre la
         *     lectura y esta escritura. **La operación no se aplicó.**
         *
         *     El cliente relee, le muestra al operador **qué cambió de lo que él tocó**, y lo deja
         *     decidir (`CU-29`). Lo que no puede hacer es releer y guardar encima: eso es sobrescribir
         *     el trabajo del otro con un paso más.
         */
        PreconditionFailed: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description La escritura llegó **sin `If-Match`**, y esta operación exige que sea condicional. **No
         *     se aplicó nada.**
         *
         *     Es el caso que RFC 6585 nombra al definir el `428`: el servidor exige un pedido
         *     condicional para evitar la actualización perdida. Tiene código propio y no comparte el
         *     `422` con los campos mal llenados porque **no lo arregla la misma persona**: esto lo
         *     arregla quien escribió la pantalla.
         *
         *     **No lleva `fields`** (`CU-49`), y **no devuelve el `ETag`**: darlo invitaría a
         *     reenviarlo tal cual, que es guardar a ciegas sobre lo que el otro dejó — lo mismo que
         *     `CU-29` descarta. Quien llegó sin testigo tiene que leer el recurso.
         */
        PreconditionRequired: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "PRECONDITION_REQUIRED",
                 *         "message": "Esta operación exige el testigo de la versión (If-Match).",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El pedido no pasó la validación. */
        ValidationFailed: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_FAILED",
                 *         "message": "Hay campos con problemas.",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y",
                 *         "fields": [
                 *           {
                 *             "field": "name",
                 *             "code": "REQUIRED",
                 *             "message": "El nombre es obligatorio."
                 *           }
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No se pudo. */
        InternalServerError: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INTERNAL_ERROR",
                 *         "message": "No se pudo completar la operación.",
                 *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Busca por nombre, parcial e insensible a mayúsculas. */
        Search: string;
        /** @description La primera es la 1. */
        Page: number;
        /**
         * @description Una por intento lógico. **Reintentar el mismo intento reusa la misma clave** — generar
         *     una nueva al reintentar anula la protección.
         *
         *     Si llega repetida con **otro cuerpo**, responde `409` con `IDEMPOTENCY_KEY_REUSE`.
         */
        IdempotencyKey: string;
        /**
         * @description Versión del recurso sobre la que el cliente cree estar operando, tal como la devolvió
         *     el `ETag` del `GET` previo.
         *
         *     **Bloqueo optimista**: si el recurso cambió entre la lectura y la escritura, el servidor
         *     responde `412` y **la operación no se aplica**. Dos operadores editando el mismo
         *     artículo no se pisan.
         *
         *     Es **obligatorio**: omitirlo responde `428 · PRECONDITION_REQUIRED`, **sin `fields`**.
         *     Nunca se aplica el cambio a ciegas.
         *
         *     Sin `fields` a propósito (`CU-49`): un encabezado que falta es un defecto de quien
         *     llama, no algo que el operador pueda corregir en un control de la pantalla. Nombrado
         *     ahí, el formulario busca un control `If-Match`, no lo encuentra, y **el rechazo
         *     desaparece entero** — ni aviso, ni campo marcado.
         * @example "7"
         */
        IfMatch: string;
        /** @description Cuántos por página. */
        Size: number;
    };
    requestBodies: never;
    headers: {
        /** @description El identificador de la solicitud, para rastrearla. */
        RequestId: string;
        /**
         * @description Versión actual del recurso. El cliente la guarda y la reenvía en `If-Match` al
         *     modificarlo.
         */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listArticles: {
        parameters: {
            query?: {
                /** @description Busca por nombre, parcial e insensible a mayúsculas. */
                search?: components["parameters"]["Search"];
                /** @description La primera es la 1. */
                page?: components["parameters"]["Page"];
                /** @description Cuántos por página. */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artículos. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": 1,
                     *           "name": "Amoxicilina 500 mg",
                     *           "price": "2450.00",
                     *           "active": true
                     *         },
                     *         {
                     *           "id": 2,
                     *           "name": "Ibuprofeno 400 mg",
                     *           "price": "1890.50",
                     *           "active": true
                     *         },
                     *         {
                     *           "id": 3,
                     *           "name": "Paracetamol 1 g",
                     *           "price": "1120.00",
                     *           "active": false
                     *         }
                     *       ],
                     *       "meta": {
                     *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y",
                     *         "page": 1,
                     *         "size": 20,
                     *         "totalItems": 3,
                     *         "totalPages": 1
                     *       }
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["Article"][];
                        meta: components["schemas"]["PageMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createArticle: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Una por intento lógico. **Reintentar el mismo intento reusa la misma clave** — generar
                 *     una nueva al reintentar anula la protección.
                 *
                 *     Si llega repetida con **otro cuerpo**, responde `409` con `IDEMPOTENCY_KEY_REUSE`.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleCreate"];
            };
        };
        responses: {
            /** @description Artículo creado. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Article"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El artículo, con su versión. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "id": 1,
                     *         "name": "Amoxicilina 500 mg",
                     *         "price": "2450.00",
                     *         "active": true
                     *       },
                     *       "meta": {
                     *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["Article"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateArticle: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Versión del recurso sobre la que el cliente cree estar operando, tal como la devolvió
                 *     el `ETag` del `GET` previo.
                 *
                 *     **Bloqueo optimista**: si el recurso cambió entre la lectura y la escritura, el servidor
                 *     responde `412` y **la operación no se aplica**. Dos operadores editando el mismo
                 *     artículo no se pisan.
                 *
                 *     Es **obligatorio**: omitirlo responde `428 · PRECONDITION_REQUIRED`, **sin `fields`**.
                 *     Nunca se aplica el cambio a ciegas.
                 *
                 *     Sin `fields` a propósito (`CU-49`): un encabezado que falta es un defecto de quien
                 *     llama, no algo que el operador pueda corregir en un control de la pantalla. Nombrado
                 *     ahí, el formulario busca un control `If-Match`, no lo encuentra, y **el rechazo
                 *     desaparece entero** — ni aviso, ni campo marcado.
                 * @example "7"
                 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Amoxicilina 500 mg",
                 *       "price": "2450.00"
                 *     }
                 */
                "application/json": components["schemas"]["ArticleCreate"];
            };
        };
        responses: {
            /** @description El artículo, con su versión nueva. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "id": 1,
                     *         "name": "Amoxicilina 500 mg",
                     *         "price": "2450.00",
                     *         "active": true
                     *       },
                     *       "meta": {
                     *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["Article"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            422: components["responses"]["ValidationFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    deactivateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El artículo, ya desactivado. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "id": 3,
                     *         "name": "Paracetamol 1 g",
                     *         "price": "1120.00",
                     *         "active": false
                     *       },
                     *       "meta": {
                     *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["Article"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    activateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1 */
                articleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El artículo, ya activo. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "id": 3,
                     *         "name": "Paracetamol 1 g",
                     *         "price": "1120.00",
                     *         "active": true
                     *       },
                     *       "meta": {
                     *         "requestId": "01JBQ2X8N4K3M7P9R2T5V8W1Y"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data: components["schemas"]["Article"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
