#!/usr/bin/env node

/**
 * **El contrato de OPE llega como artefacto** (`TAN-7`).
 *
 * Copia a `contracts/ope/` lo que el backend emite —el bundle, los tipos de
 * `openapi-typescript` y el catálogo de problemas— y, **mientras OPE-Backend no
 * emita el módulo de capacidades** (su feature 040), lo emite acá desde el
 * bundle con la forma que el frontend publica en
 * `specs/005-la-base-de-ope/contracts/contract-artifact.md`. Cuando el backend
 * tenga `generated/contract/`, esto la copia entera y deja de emitir.
 *
 * Dónde está el backend, en este orden: `--from <carpeta>` (una carpeta
 * descomprimida de un release, con la misma disposición), `OPE_BACKEND_DIR`, o
 * la carpeta hermana `../backend`.
 *
 * **Se versiona lo que deja.** Un clon sin vecino tiene que poder compilar y
 * verificar; por eso `contracts/ope/` va al repositorio y `ope-check conformity`
 * vigila que el módulo y el bundle no se despeguen.
 */

import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { join, relative, resolve, sep } from 'node:path'
import { parse } from 'yaml'

const ROOT = process.cwd()
const TARGET = join(ROOT, 'contracts', 'ope')
const HEADER =
  'GENERATED by scripts/contract-sync.mjs — interim until OPE-Backend 040 emits generated/contract/'

/** El consumidor que esta base describe. El portal pedirá el suyo en otro archivo. */
const CONSUMER = 'admin'

/** Los métodos de un path item de OpenAPI: lo demás ahí adentro no es una operación. */
const METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']

function fail(what, why) {
  console.error('')
  console.error(`  FALLA  ${what}`)
  if (why) console.error(`         ${why}`)
  console.error('')
  process.exit(1)
}

/* ── Dónde está el backend ──────────────────────────────────────────────── */

function backendDir() {
  const at = process.argv.indexOf('--from')
  if (at !== -1) {
    const given = process.argv[at + 1]
    if (!given) fail('`--from` necesita una carpeta', 'npm run contract:sync -- --from <carpeta>')
    return { dir: resolve(ROOT, given), how: `--from ${given}` }
  }
  if (process.env.OPE_BACKEND_DIR) {
    return { dir: resolve(process.env.OPE_BACKEND_DIR), how: 'OPE_BACKEND_DIR' }
  }
  return { dir: resolve(ROOT, '..', 'backend'), how: 'la carpeta hermana ../backend' }
}

const { dir: BACKEND, how } = backendDir()

if (!existsSync(BACKEND)) {
  fail(
    `No encuentro el backend en ${BACKEND} (${how})`,
    'Indicalo con OPE_BACKEND_DIR o con --from <carpeta>',
  )
}

/** Lo que se copia tal cual, y de dónde. */
const COPIED = [
  ['contracts/dist/openapi.yaml', 'openapi.yaml', 'npm run contract:bundle'],
  ['generated/api.d.ts', 'api.d.ts', 'npm run contract:types'],
  ['generated/problem-types.d.ts', 'problem-types.d.ts', 'npm run contract:types'],
]

for (const [source, , command] of COPIED) {
  const path = join(BACKEND, ...source.split('/'))
  if (!existsSync(path)) {
    fail(`El backend no tiene ${source}`, `Corré \`${command}\` en ${BACKEND}`)
  }
}

mkdirSync(TARGET, { recursive: true })

const short = (path) => relative(ROOT, path).split(sep).join('/')

console.log('')
console.log(`  backend: ${BACKEND} (${how})`)

for (const [source, name] of COPIED) {
  copyFileSync(join(BACKEND, ...source.split('/')), join(TARGET, name))
  console.log(`  copiado  ${source} → ${short(join(TARGET, name))}`)
}

/* ── Identidad del bundle ───────────────────────────────────────────────── */

const bundleBytes = readFileSync(join(TARGET, 'openapi.yaml'))
const sha256 = createHash('sha256').update(bundleBytes).digest('hex')
const bundle = parse(bundleBytes.toString('utf8'))
const version = bundle?.info?.version

if (typeof version !== 'string' || version.length === 0) {
  fail('El bundle no declara info.version', 'Sin versión no hay con qué identificar el contrato')
}

function backendCommit() {
  try {
    return execFileSync('git', ['-C', BACKEND, 'rev-parse', 'HEAD'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
  } catch {
    return undefined
  }
}

const commit = backendCommit()
const today = new Date().toISOString().slice(0, 10)

/* ── El módulo de capacidades: copiado si el backend lo emite, emitido si no ── */

const EMITTED = join(BACKEND, 'generated', 'contract')
let origin

if (existsSync(EMITTED) && statSync(EMITTED).isDirectory()) {
  for (const name of readdirSync(EMITTED)) {
    copyFileSync(join(EMITTED, name), join(TARGET, name))
    console.log(`  copiado  generated/contract/${name} → ${short(join(TARGET, name))}`)
  }
  origin = 'copiado de `generated/contract/` del backend (feature 040)'
} else {
  emitModule()
  origin =
    'emitido por `scripts/contract-sync.mjs` desde el bundle, hasta que OPE-Backend 040 lo emita'
}

function emitModule() {
  /** Cada operación del consumidor, en el orden del contrato. */
  const operations = []

  for (const [path, item] of Object.entries(bundle.paths ?? {})) {
    for (const method of METHODS) {
      const op = item?.[method]
      if (!op || typeof op !== 'object') continue
      if (!Array.isArray(op.tags) || !op.tags.includes(CONSUMER)) continue

      const id = op.operationId
      if (typeof id !== 'string' || !/^[A-Za-z_$][\w$]*$/.test(id)) {
        fail(`${method.toUpperCase()} ${path} no tiene un operationId usable`, `encontré: ${id}`)
      }

      const capabilities = op['x-required-capabilities']
      if (!Array.isArray(capabilities) || capabilities.length === 0) {
        /* Una operación sin capacidad dibujaría su botón para cualquiera (`CU-37`). */
        fail(`${id} no declara x-required-capabilities`, `${method.toUpperCase()} ${path}`)
      }
      for (const capability of capabilities) {
        if (
          typeof capability !== 'string' ||
          !/^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$/.test(capability)
        ) {
          fail(`${id} declara una capacidad que no tiene forma de tal`, `«${capability}»`)
        }
      }

      operations.push({ id, capabilities, idempotent: 'x-idempotency' in op })
    }
  }

  if (operations.length === 0) {
    fail(
      `El bundle no tiene ninguna operación con tag \`${CONSUMER}\``,
      '¿cambió la forma del contrato?',
    )
  }

  const repeated = operations.map((o) => o.id).filter((id, at, all) => all.indexOf(id) !== at)
  if (repeated.length > 0) {
    fail('Un operationId aparece dos veces en el bundle', repeated.join(', '))
  }

  const vocabulary = [...new Set(operations.flatMap((o) => o.capabilities))].sort()
  const quoted = (list) => list.map((each) => `'${each}'`).join(', ')
  const banner = `// ${HEADER}\n// DO NOT EDIT BY HAND. Regenerate with: npm run contract:sync\n`

  const js = `${banner}
/** The contract this module was derived from. */
export const CONTRACT = { version: '${version}', sha256: '${sha256}' }

/** The consumer this module describes: its operations and its vocabulary. */
export const CONSUMER = '${CONSUMER}'

/** Every capability some ${CONSUMER} operation requires, sorted. */
export const CAPABILITIES = [${quoted(vocabulary)}]

/** What the contract demands of each ${CONSUMER} operation. */
export const OPERATIONS = {
${operations
  .map(
    (o) => `  ${o.id}: { capabilities: [${quoted(o.capabilities)}], idempotent: ${o.idempotent} },`,
  )
  .join('\n')}
}
`

  const dts = `${banner}
/** The contract this module was derived from. */
export declare const CONTRACT: {
  readonly version: '${version}'
  readonly sha256: '${sha256}'
}

/** The consumer this module describes: its operations and its vocabulary. */
export declare const CONSUMER: '${CONSUMER}'

/** Every capability some ${CONSUMER} operation requires, sorted. */
export declare const CAPABILITIES: readonly [${quoted(vocabulary)}]
export type Capability = (typeof CAPABILITIES)[number]

/** What the contract demands of each ${CONSUMER} operation. */
export declare const OPERATIONS: {
${operations
  .map(
    (o) =>
      `  readonly ${o.id}: {\n    readonly capabilities: readonly [${quoted(o.capabilities)}]\n    readonly idempotent: ${o.idempotent}\n  }`,
  )
  .join('\n')}
}
export type OperationId = keyof typeof OPERATIONS
`

  const identity = {
    $comment: `${HEADER} — DO NOT EDIT BY HAND.`,
    version,
    sha256,
    ...(commit ? { backendCommit: commit } : {}),
  }

  writeFileSync(join(TARGET, 'capabilities.js'), js, 'utf8')
  writeFileSync(join(TARGET, 'capabilities.d.ts'), dts, 'utf8')
  writeFileSync(join(TARGET, 'identity.json'), `${JSON.stringify(identity, null, 2)}\n`, 'utf8')

  console.log(
    `  emitido  capabilities.js, capabilities.d.ts, identity.json: ${operations.length} operaciones ${CONSUMER}, ${vocabulary.length} capacidades`,
  )
}

/* ── El README: de qué commit salió, y cuándo ───────────────────────────── */

const readme = `# \`contracts/ope/\` — el contrato de OPE, como artefacto

**No se edita a mano.** Lo deja \`npm run contract:sync\` (\`scripts/contract-sync.mjs\`), y
\`ope-check conformity\` verifica que el módulo de capacidades y el bundle no se hayan despegado.

| | |
|---|---|
| Versión del contrato | \`${version}\` |
| \`sha256\` del bundle | \`${sha256}\` |
| Commit de OPE-Backend | ${commit ? `\`${commit}\`` : '_desconocido: el backend no era un clon de git_'} |
| Sincronizado | ${today} |
| Módulo de capacidades | ${origin} |

## Los archivos

| archivo | de dónde sale | quién lo lee |
|---|---|---|
| \`openapi.yaml\` | \`contracts/dist/openapi.yaml\` del backend, sin tocar | \`conformity\`; una persona |
| \`api.d.ts\` | \`generated/api.d.ts\` del backend (openapi-typescript) | \`openapi-fetch\` en \`apps/*/src/api/ope/\`; \`conformity\` |
| \`problem-types.d.ts\` | \`generated/problem-types.d.ts\` del backend | \`@ope/core\` (\`ProblemSlug\`) |
| \`capabilities.js\` + \`capabilities.d.ts\` | el módulo de \`TAN-7\`: operación → capacidades e idempotencia, y el vocabulario del consumidor \`${CONSUMER}\` | \`operation()\`, \`conformity\`, la sesión falsa |
| \`identity.json\` | versión y \`sha256\` del bundle, y el commit del backend | \`conformity\`; este README |

La forma del módulo es la que el frontend publica en
\`specs/005-la-base-de-ope/contracts/contract-artifact.md\`; es lo que OPE-Backend 040 tiene que emitir
en \`generated/contract/\`. Cuando lo emita, el sincronizador copia en vez de emitir.
`

writeFileSync(join(TARGET, 'README.md'), readme, 'utf8')

console.log(`  escrito  ${short(join(TARGET, 'README.md'))}`)
console.log('')
console.log(
  `  contrato ${version} · sha256 ${sha256.slice(0, 12)}… · backend ${commit ? commit.slice(0, 7) : '(sin git)'}`,
)
console.log('')
